# -*- coding: utf-8 -*-
# noon Clinic · catálogo de la clínica (cirugía plástica + medicina estética). SIN PRECIOS.
# Los tiempos son orientativos: el plan exacto lo define el especialista en la valoración.

# ---------------------------------------------------------------- ESPECIALISTAS
# foto: archivo dentro de assets/equipo/ (vacío = se muestra la inicial mientras llega la foto)
ESPECIALISTAS = [
    {"slug": "fernando-ruiz", "nombre": "Dr. Fernando Ruiz", "rol": "Cirujano plástico", "area": "cirugia",
     "foto": "fernando-ruiz.jpg",
     "bio": "Cirujano plástico del equipo noon Clinic.",
     "detalle": []},
    {"slug": "valeria-enciso", "nombre": "Dra. Valeria Enciso", "rol": "Médica estética", "area": "estetica",
     "foto": "valeria-enciso.jpg",
     "bio": "Médica estética del equipo noon Clinic.",
     "detalle": []},
]

# ---------------------------------------------------------------- CIRUGÍA PLÁSTICA
CATEGORIAS_CX = [
    ("rostro", "Rostro", "Párpados, nariz, mentón, orejas y rejuvenecimiento facial.", "seda-clara"),
    ("senos", "Senos", "Volumen, posición, reducción y recambio de implantes.", "seda-burdeos"),
    ("cuerpo", "Contorno corporal", "Lipoescultura, abdomen, glúteos, brazos y muslos.", "seda-cafe"),
    ("combinadas", "Combinadas e íntima", "Procedimientos combinados y cirugía íntima.", "seda-horizonte"),
]

# Cada cirugía: datos orientativos (duración, anestesia, incapacidad, resultado final)
CIRUGIAS_NOON = [
    # ---------- ROSTRO
    {"slug": "blefaroplastia", "cat": "rostro", "nombre": "Blefaroplastia",
     "corto": "Mirada descansada: se trata el exceso de piel y las bolsas de los párpados.",
     "que_es": ["Cirugía de los párpados superiores, inferiores o ambos. Retira o reposiciona el exceso de piel y grasa que da una mirada cansada o pesada.",
                "Las incisiones siguen los pliegues naturales del párpado para que la cicatriz quede prácticamente oculta."],
     "ideal": ["Exceso de piel en el párpado superior", "Bolsas o hundimiento bajo los ojos", "Mirada cansada aunque hayas descansado"],
     "datos": ("1 a 2 horas", "Local con sedación o general", "7 a 10 días", "2 a 3 meses"),
     "recuperacion": [("Primeros días", "Inflamación y morados leves. Compresas frías y cabeza elevada."), ("Semana 1", "Retiro de puntos."), ("Semanas 2 a 3", "Vuelves a tu rutina y al maquillaje."), ("Mes 2 a 3", "La cicatriz madura y el resultado se asienta.")],
     "faq": [("¿Se nota la cicatriz?", "Queda en el pliegue natural del párpado o justo bajo las pestañas, por lo que suele ser muy discreta una vez madura."),
             ("¿Puedo combinarla con otro procedimiento?", "Sí, con frecuencia se combina con lifting de cejas o facial. Se define en la valoración.")]},
    {"slug": "rinoplastia", "cat": "rostro", "nombre": "Rinoplastia",
     "corto": "Armonía entre la nariz y el rostro, cuidando también la respiración.",
     "que_es": ["Cirugía que modifica la forma, el tamaño o la proporción de la nariz. Cuando hay problemas respiratorios puede hacerse junto a una septoplastia (rinoseptoplastia).",
                "El objetivo es una nariz natural, que se vea tuya y en equilibrio con el resto del rostro."],
     "ideal": ["Giba o dorso prominente", "Punta ancha, caída o poco definida", "Dificultad para respirar por el tabique"],
     "datos": ("2 a 3 horas", "General", "10 a 15 días", "Hasta 12 meses"),
     "recuperacion": [("Semana 1", "Férula nasal e inflamación alrededor de los ojos."), ("Semana 2", "Retiro de férula; vuelves a actividades suaves."), ("Mes 1 a 3", "La mayor parte de la inflamación baja."), ("Año 1", "La punta termina de definirse.")],
     "faq": [("¿Cuándo veo el resultado final?", "La nariz cambia mucho en los primeros meses, pero la punta termina de definirse alrededor del año."),
             ("¿Me van a taponar la nariz?", "Depende de la técnica y tu caso. Tu cirujano te lo explica en la valoración.")]},
    {"slug": "lifting-facial", "cat": "rostro", "nombre": "Lifting facial y de cuello",
     "corto": "Rejuvenecimiento profundo que reposiciona tejidos del rostro y el cuello.",
     "que_es": ["Cirugía que reposiciona las capas profundas del rostro y el cuello y retira el exceso de piel, para tratar la flacidez de mejillas, línea mandibular y cuello.",
                "Busca un resultado descansado y natural, no un rostro estirado."],
     "ideal": ["Flacidez en mejillas y papada", "Pérdida de definición mandibular", "Bandas o piel suelta en el cuello"],
     "datos": ("3 a 5 horas", "General o sedación", "2 a 3 semanas", "3 a 6 meses"),
     "recuperacion": [("Semana 1", "Vendaje, inflamación y reposo con cabeza elevada."), ("Semana 2", "Retiro de puntos y baja la inflamación."), ("Semanas 3 a 4", "Retomas la vida social."), ("Mes 3 a 6", "Resultado asentado.")],
     "faq": [("¿Cuánto dura el resultado?", "Muchos años, aunque el envejecimiento natural continúa. Los cuidados de piel ayudan a mantenerlo."),
             ("¿Quedan cicatrices visibles?", "Se ubican alrededor de la oreja y en el cuero cabelludo, donde se disimulan con facilidad.")]},
    {"slug": "bichectomia", "cat": "rostro", "nombre": "Bichectomía",
     "corto": "Mejillas más definidas retirando parte de las bolsas de Bichat.",
     "que_es": ["Procedimiento que retira parte de la grasa de las bolsas de Bichat, en las mejillas, para afinar el tercio medio del rostro.",
                "Se hace por dentro de la boca, así que no deja cicatrices visibles."],
     "ideal": ["Rostro redondo por volumen en mejillas", "Deseo de mayor definición facial", "Buena calidad de piel"],
     "datos": ("30 a 60 minutos", "Local", "3 a 5 días", "3 a 6 meses"),
     "recuperacion": [("Primeros días", "Inflamación y dieta blanda."), ("Semana 1", "Vuelves a tu rutina."), ("Mes 1 a 3", "La cara se va afinando."), ("Mes 6", "Resultado final.")],
     "faq": [("¿Deja cicatriz?", "No visible: la incisión es por dentro de la boca."),
             ("¿Es para todos?", "No. Si el rostro ya es delgado puede envejecerlo; por eso se valora con cuidado.")]},
    {"slug": "mentoplastia", "cat": "rostro", "nombre": "Mentoplastia",
     "corto": "Un mentón en proporción con la nariz y el perfil.",
     "que_es": ["Cirugía del mentón para darle proyección o reducirlo, con implante o remodelando el hueso según el caso.",
                "Mejora el perfil y a menudo se combina con rinoplastia o lipopapada."],
     "ideal": ["Mentón retraído o poco proyectado", "Perfil desequilibrado", "Deseo de definir la línea mandibular"],
     "datos": ("1 a 2 horas", "General o local con sedación", "7 a 10 días", "3 meses"),
     "recuperacion": [("Semana 1", "Inflamación y vendaje de soporte."), ("Semana 2", "Vuelves a tu rutina."), ("Mes 1 a 3", "Resultado asentado.")],
     "faq": [("¿Se puede hacer sin cirugía?", "En algunos casos se mejora con ácido hialurónico. En la valoración te decimos qué opción tiene sentido para ti.")]},
    {"slug": "otoplastia", "cat": "rostro", "nombre": "Otoplastia",
     "corto": "Corrige las orejas prominentes con cicatriz oculta detrás de la oreja.",
     "que_es": ["Cirugía que acerca las orejas a la cabeza o corrige su forma. La incisión queda en la parte de atrás de la oreja.",
                "Se puede hacer en adultos y en niños a partir de los 6 años aproximadamente."],
     "ideal": ["Orejas prominentes o en 'asa'", "Asimetría entre una oreja y otra", "Incomodidad con la forma de las orejas"],
     "datos": ("1 a 2 horas", "Local con sedación o general", "7 días", "1 a 3 meses"),
     "recuperacion": [("Semana 1", "Vendaje en la cabeza."), ("Semanas 2 a 6", "Banda para dormir."), ("Mes 1 a 3", "Resultado estable.")],
     "faq": [("¿Duele?", "Hay molestia los primeros días, controlada con analgésicos.")]},
    {"slug": "lipopapada", "cat": "rostro", "nombre": "Lipopapada",
     "corto": "Define el cuello y la línea mandibular retirando grasa de la papada.",
     "que_es": ["Liposucción de la papada a través de incisiones mínimas bajo el mentón y detrás de las orejas.",
                "Es ideal cuando la piel conserva buena elasticidad; si hay flacidez importante, puede requerir lifting de cuello."],
     "ideal": ["Grasa localizada en la papada", "Buena elasticidad de la piel", "Deseo de definir el ángulo del cuello"],
     "datos": ("1 hora", "Local con sedación", "5 a 7 días", "3 meses"),
     "recuperacion": [("Semana 1", "Mentonera de compresión."), ("Semanas 2 a 4", "Mentonera en las noches."), ("Mes 3", "Resultado final.")],
     "faq": [("¿Necesito usar mentonera?", "Sí, ayuda a que la piel se adapte al nuevo contorno. Tu especialista te dice por cuánto tiempo.")]},

    # ---------- SENOS
    {"slug": "mamoplastia-de-aumento", "cat": "senos", "nombre": "Mamoplastia de aumento",
     "corto": "Más volumen y mejor forma con implantes elegidos a tu medida.",
     "que_es": ["Cirugía que aumenta el volumen y mejora la forma de los senos con implantes mamarios.",
                "Tamaño, perfil y ubicación del implante se deciden contigo en la valoración, según tus medidas y lo que quieres lograr."],
     "ideal": ["Senos pequeños para tu cuerpo", "Pérdida de volumen tras embarazo o baja de peso", "Diferencia de tamaño entre un seno y otro"],
     "datos": ("1,5 a 2 horas", "General", "Aprox. 1 semana", "3 a 6 meses"),
     "recuperacion": [("Día de la cirugía", "Sales con brasier posquirúrgico. Necesitas acompañante."), ("Semana 1", "Reposo relativo y primer control."), ("Semanas 2 a 4", "Vuelves poco a poco a tu rutina."), ("Mes 3 a 6", "Los implantes se asientan y toman su forma natural.")],
     "faq": [("¿Cómo se escoge el tamaño?", "Según el ancho de tu tórax, tu piel y el resultado que buscas. El objetivo es que se vea proporcionado."),
             ("¿Podré lactar después?", "En la mayoría de los casos, sí. Cuéntale a tu cirujano si planeas un embarazo."),
             ("¿Los implantes hay que cambiarlos?", "No tienen fecha de vencimiento fija, pero requieren control periódico y pueden necesitar recambio en algún momento.")]},
    {"slug": "mastopexia", "cat": "senos", "nombre": "Mastopexia",
     "corto": "Levanta y reafirma el seno, con o sin implantes.",
     "que_es": ["Cirugía que levanta el seno caído: retira el exceso de piel, da nueva forma al tejido y sube la areola y el pezón.",
                "Puede hacerse con implantes, si además quieres volumen, o solo con tu propio tejido."],
     "ideal": ["Senos caídos tras embarazos, lactancia o cambios de peso", "Areola y pezón que apuntan hacia abajo", "Sensación de seno 'vacío' arriba"],
     "datos": ("3 a 5 horas", "General", "2 a 3 semanas", "Aprox. 6 meses"),
     "recuperacion": [("Día de la cirugía", "Sales con brasier posquirúrgico. Necesitas acompañante."), ("Semana 1", "Reposo relativo y cuidado de heridas."), ("Semanas 2 a 4", "Regreso gradual, sin esfuerzos."), ("Mes 6", "Resultado final; las cicatrices siguen aclarando hasta el año.")],
     "faq": [("¿Con o sin implantes?", "Si te gusta tu volumen, sin implantes. Si además quieres llenar la parte superior, con implantes. Lo definimos contigo."),
             ("¿Cómo son las cicatrices?", "Dependen de cuánto haya que levantar: alrededor de la areola, vertical o en forma de ancla.")]},
    {"slug": "mamoplastia-de-reduccion", "cat": "senos", "nombre": "Mamoplastia de reducción",
     "corto": "Senos más livianos y proporcionados; alivio de espalda y cuello.",
     "que_es": ["Cirugía que reduce el tamaño y el peso de los senos retirando tejido mamario, grasa y piel, y los reposiciona más arriba.",
                "Además del cambio estético, suele aliviar el dolor de espalda, cuello y hombros."],
     "ideal": ["Senos grandes que causan dolor o molestia", "Marcas de los tirantes en los hombros", "Dificultad para hacer ejercicio o encontrar ropa"],
     "datos": ("3 a 4 horas", "General", "2 a 3 semanas", "Aprox. 6 meses"),
     "recuperacion": [("Semana 1", "Brasier posquirúrgico y reposo relativo."), ("Semanas 2 a 4", "Regreso gradual a tus actividades."), ("Mes 6", "Forma definitiva.")],
     "faq": [("¿Podré lactar?", "Es posible en muchos casos, pero no se puede garantizar. Coméntalo en tu valoración.")]},
    {"slug": "recambio-de-implantes", "cat": "senos", "nombre": "Recambio o retiro de implantes",
     "corto": "Actualiza, cambia de tamaño o retira tus implantes con seguridad.",
     "que_es": ["Cirugía para cambiar implantes antiguos, modificar su tamaño o retirarlos (explantación), con o sin levantamiento del seno.",
                "Cuando hay cápsula endurecida (contractura capsular) se puede tratar en la misma cirugía."],
     "ideal": ["Implantes con muchos años", "Deseo de otro tamaño", "Contractura capsular, molestia o deseo de retirarlos"],
     "datos": ("2 a 4 horas", "General", "1 a 2 semanas", "3 a 6 meses"),
     "recuperacion": [("Semana 1", "Brasier posquirúrgico y reposo relativo."), ("Semanas 2 a 4", "Regreso gradual."), ("Mes 3 a 6", "Resultado asentado.")],
     "faq": [("Si retiro los implantes, ¿cómo quedan los senos?", "Depende de tu piel y tejido. Muchas veces se combina con mastopexia para que queden firmes.")]},
    {"slug": "ginecomastia", "cat": "senos", "nombre": "Ginecomastia",
     "corto": "Pecho masculino más plano y definido.",
     "que_es": ["Cirugía para hombres que retira el exceso de tejido mamario y grasa del pecho, con liposucción, resección de la glándula o ambas.",
                "Se hace por incisiones pequeñas, habitualmente en el borde de la areola."],
     "ideal": ["Aumento de volumen en el pecho masculino", "Tejido que no cede con ejercicio", "Incomodidad al usar ropa ajustada"],
     "datos": ("1 a 2 horas", "General o sedación", "7 a 10 días", "3 a 6 meses"),
     "recuperacion": [("Semana 1", "Chaleco de compresión."), ("Semanas 2 a 4", "Compresión y regreso gradual al ejercicio."), ("Mes 3 a 6", "Resultado final.")],
     "faq": [("¿Vuelve a aparecer?", "El tejido retirado no vuelve, pero cambios de peso o ciertos medicamentos pueden influir.")]},

    # ---------- CONTORNO CORPORAL
    {"slug": "liposuccion", "cat": "cuerpo", "nombre": "Liposucción y lipoescultura",
     "corto": "Define tu contorno retirando grasa localizada.",
     "que_es": ["Retira la grasa localizada que no cede con dieta ni ejercicio y esculpe el contorno de abdomen, cintura, espalda, brazos, muslos u otras zonas.",
                "Moldea el cuerpo; no es un método para bajar de peso. La cantidad de grasa que se retira tiene un límite, y ese límite lo pone tu salud."],
     "ideal": ["Grasa localizada que no cede", "Peso estable y cercano a tu peso saludable", "Deseo de definir cintura, abdomen o espalda"],
     "datos": ("2 a 5 horas", "General o raquídea", "2 a 3 semanas", "3 a 6 meses"),
     "recuperacion": [("Día de la cirugía", "Sales con prenda de compresión. Necesitas acompañante."), ("Semana 1", "Caminatas cortas y drenajes linfáticos."), ("Semanas 2 a 4", "Prenda y masajes; vuelves a tu rutina."), ("Mes 3 a 6", "El cuerpo desinflama por completo.")],
     "faq": [("¿La lipo sirve para bajar de peso?", "No. Moldea y define; los mejores resultados se ven en personas con peso estable."),
             ("¿Los masajes son necesarios?", "Sí: ayudan a desinflamar y a que el resultado quede parejo.")]},
    {"slug": "lipotransferencia-glutea", "cat": "cuerpo", "nombre": "Lipotransferencia glútea",
     "corto": "Volumen y forma en glúteos con tu propia grasa.",
     "que_es": ["Combina liposucción de zonas como abdomen o espalda con la transferencia de esa grasa, purificada, a los glúteos para darles volumen y forma.",
                "Se realiza con técnicas que priorizan tu seguridad; una parte de la grasa transferida se reabsorbe en los primeros meses."],
     "ideal": ["Deseo de más proyección o forma en glúteos", "Grasa suficiente en otras zonas", "Preferencia por no usar implantes"],
     "datos": ("3 a 5 horas", "General", "2 a 3 semanas", "Aprox. 6 meses"),
     "recuperacion": [("Semanas 1 a 3", "Evitar presión directa sobre glúteos según indicación. Prenda y masajes."), ("Mes 1 a 2", "Regreso gradual al ejercicio."), ("Mes 6", "Volumen estable.")],
     "faq": [("¿Cuánto volumen se mantiene?", "Una parte de la grasa se reabsorbe. Lo que se integra en los primeros meses es permanente.")]},
    {"slug": "abdominoplastia", "cat": "cuerpo", "nombre": "Abdominoplastia",
     "corto": "Abdomen plano y firme: piel, grasa y músculo.",
     "que_es": ["Retira el exceso de piel y grasa del abdomen y, cuando hace falta, repara la separación de los músculos abdominales (diástasis).",
                "Se suele combinar con liposucción para definir la cintura. La cicatriz queda baja, cubierta por la ropa interior."],
     "ideal": ["Piel sobrante tras embarazos o pérdida de peso", "Diástasis de rectos", "Estrías en la parte baja del abdomen"],
     "datos": ("3 a 4 horas", "General", "2 a 3 semanas", "6 a 12 meses"),
     "recuperacion": [("Semana 1", "Caminas ligeramente inclinada; faja y reposo relativo."), ("Semanas 2 a 4", "Regreso gradual a tus actividades."), ("Mes 1 a 3", "Ejercicio con autorización."), ("Año 1", "La cicatriz madura.")],
     "faq": [("¿Puedo tener hijos después?", "Sí, pero lo ideal es operarse cuando no planees más embarazos, para conservar el resultado.")]},
    {"slug": "mini-abdominoplastia", "cat": "cuerpo", "nombre": "Mini abdominoplastia",
     "corto": "Para piel sobrante solo en la parte baja del abdomen.",
     "que_es": ["Versión más corta de la abdominoplastia: trata el exceso de piel y grasa por debajo del ombligo, con una cicatriz más pequeña.",
                "Indicada cuando el problema es leve y se concentra en la parte baja."],
     "ideal": ["Piel sobrante leve bajo el ombligo", "Buen tono en la parte alta del abdomen", "Deseo de una cicatriz más corta"],
     "datos": ("Aprox. 2 horas", "General o raquídea", "10 a 14 días", "3 a 6 meses"),
     "recuperacion": [("Semana 1", "Faja y reposo relativo."), ("Semanas 2 a 3", "Regreso a tu rutina."), ("Mes 3 a 6", "Resultado asentado.")],
     "faq": [("¿Cómo sé si necesito mini o completa?", "Depende de cuánta piel sobra y de si hay diástasis. Se define en la valoración.")]},
    {"slug": "braquioplastia", "cat": "cuerpo", "nombre": "Braquioplastia",
     "corto": "Brazos firmes, sin piel colgante.",
     "que_es": ["Cirugía que retira el exceso de piel y grasa de la cara interna de los brazos, frecuente tras una gran pérdida de peso.",
                "La cicatriz queda en la cara interna del brazo, la zona menos visible."],
     "ideal": ["Piel colgante en brazos", "Pérdida importante de peso", "Flacidez que no mejora con ejercicio"],
     "datos": ("2 a 3 horas", "General", "Aprox. 2 semanas", "Aprox. 6 meses"),
     "recuperacion": [("Semanas 1 a 2", "Prenda de compresión en brazos."), ("Semanas 3 a 6", "Regreso gradual al ejercicio."), ("Mes 6", "Resultado final.")],
     "faq": [("¿Se puede hacer solo con lipo?", "Si la piel es firme, a veces sí. Si hay piel sobrante, la braquioplastia es la opción.")]},
    {"slug": "lifting-de-muslos", "cat": "cuerpo", "nombre": "Lifting de muslos",
     "corto": "Muslos más firmes tratando la flacidez interna.",
     "que_es": ["Retira el exceso de piel y grasa de la cara interna de los muslos y levanta los tejidos.",
                "Suele indicarse tras una gran pérdida de peso."],
     "ideal": ["Flacidez en cara interna de muslos", "Roce entre muslos al caminar", "Piel sobrante tras bajar de peso"],
     "datos": ("2 a 4 horas", "General", "2 a 3 semanas", "Aprox. 6 meses"),
     "recuperacion": [("Semanas 1 a 3", "Prenda de compresión y reposo relativo."), ("Mes 1 a 2", "Regreso gradual."), ("Mes 6", "Resultado final.")],
     "faq": [("¿Dónde queda la cicatriz?", "En la ingle y, según el caso, en la cara interna del muslo.")]},
    {"slug": "cirugia-post-bariatrica", "cat": "cuerpo", "nombre": "Cirugía tras gran pérdida de peso",
     "corto": "Body lift y cirugías para retirar la piel sobrante después de bajar mucho de peso.",
     "que_es": ["Después de una cirugía bariátrica o de una gran pérdida de peso suele quedar piel sobrante en abdomen, espalda, brazos, muslos o senos.",
                "Se planea por etapas según tus prioridades y tu salud, para devolverle forma al cuerpo."],
     "ideal": ["Pérdida de peso importante y estable", "Piel sobrante en varias zonas", "Buen estado nutricional"],
     "datos": ("4 a 6 horas por etapa", "General", "3 a 4 semanas", "6 a 12 meses"),
     "recuperacion": [("Semanas 1 a 4", "Prendas de compresión y acompañamiento cercano."), ("Mes 2 a 3", "Regreso gradual al ejercicio."), ("Año 1", "Resultado maduro.")],
     "faq": [("¿Cuánto tiempo después de la bariátrica me puedo operar?", "Cuando tu peso lleve varios meses estable y tu nutrición esté en orden. Lo evaluamos con tus exámenes.")]},

    # ---------- COMBINADAS E ÍNTIMA
    {"slug": "mommy-makeover", "cat": "combinadas", "nombre": "Mommy makeover",
     "corto": "Senos y abdomen en un solo tiempo quirúrgico, después de la maternidad.",
     "que_es": ["Combina procedimientos como mastopexia o aumento mamario con abdominoplastia y liposucción, para recuperar la forma del cuerpo después de los embarazos.",
                "Se planea a tu medida y solo cuando es seguro hacerlos en una misma cirugía."],
     "ideal": ["Cambios en senos y abdomen tras embarazos", "No planeas más embarazos", "Buen estado de salud"],
     "datos": ("4 a 6 horas", "General", "3 a 4 semanas", "Aprox. 6 meses"),
     "recuperacion": [("Semana 1", "Reposo relativo con acompañante."), ("Semanas 2 a 4", "Prendas, masajes y controles."), ("Mes 1 a 3", "Ejercicio con autorización."), ("Mes 6", "Resultado asentado.")],
     "faq": [("¿Es seguro hacer todo junto?", "Solo si tu salud lo permite y el tiempo quirúrgico es razonable. Si no, se hace por etapas.")]},
    {"slug": "labioplastia", "cat": "combinadas", "nombre": "Labioplastia",
     "corto": "Cirugía íntima para reducir o armonizar los labios menores.",
     "que_es": ["Reduce o remodela los labios menores cuando generan molestia física (roce, irritación) o incomodidad estética.",
                "Es un procedimiento corto, realizado con total discreción."],
     "ideal": ["Molestia al hacer ejercicio o con ropa ajustada", "Asimetría", "Incomodidad con la apariencia"],
     "datos": ("Aprox. 1 hora", "Local con sedación o raquídea", "7 a 10 días", "1 a 3 meses"),
     "recuperacion": [("Semana 1", "Inflamación y cuidados locales."), ("Semanas 2 a 4", "Regreso gradual; relaciones y ejercicio según indicación."), ("Mes 1 a 3", "Resultado final.")],
     "faq": [("¿Afecta la sensibilidad?", "La técnica cuida la sensibilidad. Tu especialista te explica los riesgos en la valoración.")]},
]

# ---------------------------------------------------------------- MEDICINA ESTÉTICA
CATEGORIAS_ME = [
    ("inyectables", "Inyectables", "Toxina botulínica, ácido hialurónico, bioestimuladores e hilos.", "seda-champan"),
    ("piel", "Piel", "Calidad, luminosidad, manchas y textura.", "seda-clara"),
    ("tecnologias", "Tecnologías", "Láser, HIFU, radiofrecuencia y tratamientos corporales.", "seda-noche"),
    ("bienestar", "Bienestar", "Sueroterapia, manejo médico del peso y nutrición.", "seda-horizonte"),
]
# datos = (sesiones, duración de la sesión, recuperación, resultado)
TRATAMIENTOS = [
    {"slug": "toxina-botulinica", "cat": "inyectables", "nombre": "Toxina botulínica",
     "corto": "Suaviza las líneas de expresión de frente, entrecejo y patas de gallo.",
     "que_es": ["Relaja de forma temporal los músculos que forman arrugas de expresión. Bien aplicada, el rostro conserva su expresión: se ve descansado, no congelado.",
                "También se usa para el bruxismo, la sudoración excesiva y el perfilado de cejas."],
     "ideal": ["Líneas en frente, entrecejo o patas de gallo", "Bruxismo", "Sudoración excesiva en axilas o manos"],
     "datos": ("1 sesión (control a los 15 días)", "20 a 30 minutos", "Inmediata", "Efecto en 3 a 7 días; dura 4 a 6 meses"),
     "faq": [("¿Me voy a ver congelada?", "No es el objetivo. La dosis y los puntos se ajustan para que conserves tu expresión."),
             ("¿Qué cuidados hay después?", "No acostarte ni masajear la zona durante unas horas y evitar ejercicio intenso ese día.")]},
    {"slug": "acido-hialuronico", "cat": "inyectables", "nombre": "Ácido hialurónico",
     "corto": "Labios, ojeras, surcos, mentón, mandíbula y rinomodelación.",
     "que_es": ["Relleno reabsorbible que devuelve volumen, hidrata y define. Se usa en labios, ojeras, surcos, pómulos, mentón, mandíbula y para perfilar la nariz sin cirugía.",
                "Se busca armonía: realzar lo tuyo, sin cambiar quién eres."],
     "ideal": ["Pérdida de volumen facial", "Labios finos o poco definidos", "Ojeras hundidas o surcos marcados"],
     "datos": ("1 sesión", "30 a 60 minutos", "Inflamación leve 2 a 5 días", "Inmediato; dura 6 a 18 meses según la zona"),
     "faq": [("¿Se puede revertir?", "Sí, el ácido hialurónico se puede disolver con una enzima si fuera necesario."),
             ("¿Duele?", "Se usa anestesia tópica y la mayoría de productos trae anestésico incorporado.")]},
    {"slug": "bioestimuladores", "cat": "inyectables", "nombre": "Bioestimuladores de colágeno",
     "corto": "Firmeza y calidad de piel estimulando tu propio colágeno.",
     "que_es": ["Sustancias como la hidroxiapatita de calcio o el ácido poli-L-láctico que estimulan la producción de colágeno para mejorar la firmeza y la flacidez de rostro y cuerpo.",
                "El resultado es progresivo y natural."],
     "ideal": ["Flacidez leve a moderada", "Piel sin firmeza", "Prevención del envejecimiento"],
     "datos": ("1 a 3 sesiones", "30 a 45 minutos", "Inflamación leve 1 a 3 días", "Progresivo en 2 a 3 meses; dura 12 a 24 meses"),
     "faq": [("¿Cuándo veo resultados?", "La mejoría es gradual y se aprecia entre el segundo y el tercer mes.")]},
    {"slug": "hilos-tensores", "cat": "inyectables", "nombre": "Hilos tensores",
     "corto": "Efecto lifting sin cirugía para flacidez leve.",
     "que_es": ["Hilos reabsorbibles que se colocan bajo la piel para reposicionar tejidos y estimular colágeno en mejillas, mandíbula y cuello.",
                "Indicados para flacidez leve a moderada; no reemplazan un lifting quirúrgico."],
     "ideal": ["Flacidez leve en mejillas o mandíbula", "Deseo de un efecto lifting sin cirugía"],
     "datos": ("1 sesión", "45 a 60 minutos", "3 a 7 días", "Inmediato y progresivo; dura 12 a 18 meses"),
     "faq": [("¿Se notan los hilos?", "No, quedan bajo la piel y se reabsorben con el tiempo.")]},
    {"slug": "skinboosters", "cat": "piel", "nombre": "Skinboosters",
     "corto": "Hidratación profunda y luminosidad desde adentro.",
     "que_es": ["Microinyecciones de ácido hialurónico no reticulado que hidratan en profundidad y mejoran la textura, la elasticidad y el brillo de la piel.",
                "Se aplican en rostro, cuello, escote y manos."],
     "ideal": ["Piel opaca o deshidratada", "Líneas finas", "Textura irregular"],
     "datos": ("2 a 3 sesiones", "30 minutos", "Pequeñas pápulas 24 a 48 horas", "En 4 a 6 semanas; dura 6 a 9 meses"),
     "faq": [("¿Cambia mi rostro?", "No da volumen: mejora la calidad de la piel.")]},
    {"slug": "plasma-rico-en-plaquetas", "cat": "piel", "nombre": "Plasma rico en plaquetas",
     "corto": "Regeneración de piel y cabello con tus propias plaquetas.",
     "que_es": ["Se obtiene de una pequeña muestra de tu sangre y se aplica en la piel o el cuero cabelludo para estimular la regeneración.",
                "Mejora textura, luminosidad y ayuda en algunos tipos de caída del cabello."],
     "ideal": ["Piel apagada o con textura irregular", "Caída del cabello", "Cicatrices leves de acné"],
     "datos": ("3 sesiones", "45 a 60 minutos", "Enrojecimiento 24 a 48 horas", "Progresivo"),
     "faq": [("¿Es seguro?", "Es tu propio plasma, por lo que el riesgo de reacción es muy bajo.")]},
    {"slug": "peelings", "cat": "piel", "nombre": "Peelings químicos",
     "corto": "Renovación de la piel para manchas, acné y textura.",
     "que_es": ["Aplicación de ácidos en concentraciones médicas que renuevan las capas superficiales de la piel.",
                "Se elige el tipo y la profundidad según tu piel y tu objetivo."],
     "ideal": ["Manchas", "Acné o marcas de acné", "Poros y textura"],
     "datos": ("Serie de 3 a 6 sesiones", "30 minutos", "Descamación 3 a 7 días", "Progresivo en cada sesión"),
     "faq": [("¿Puedo tomar sol?", "Debes protegerte del sol de forma estricta durante el tratamiento.")]},
    {"slug": "microagujas", "cat": "piel", "nombre": "Microagujas",
     "corto": "Estimula colágeno para cicatrices, poros y firmeza.",
     "que_es": ["Microperforaciones controladas que activan la reparación natural de la piel y la producción de colágeno. Pueden combinarse con activos.",
                "Mejora cicatrices de acné, poros, textura y firmeza."],
     "ideal": ["Cicatrices de acné", "Poros dilatados", "Textura irregular"],
     "datos": ("3 a 4 sesiones", "45 minutos", "Enrojecimiento 1 a 3 días", "Progresivo"),
     "faq": [("¿Duele?", "Se aplica anestesia tópica antes; la sensación es tolerable.")]},
    {"slug": "limpieza-facial-medica", "cat": "piel", "nombre": "Limpieza facial médica",
     "corto": "Piel limpia, equilibrada y lista para otros tratamientos.",
     "que_es": ["Limpieza profunda con protocolo médico: extracción, exfoliación y activos según tu tipo de piel.",
                "Ideal como mantenimiento o como preparación para otros tratamientos."],
     "ideal": ["Poros obstruidos", "Piel grasa o mixta", "Mantenimiento mensual"],
     "datos": ("Mensual", "60 minutos", "Ninguna", "Inmediato"),
     "faq": [("¿Cada cuánto me la hago?", "Por lo general una vez al mes, según tu piel.")]},
    {"slug": "manchas-y-melasma", "cat": "piel", "nombre": "Manchas y melasma",
     "corto": "Plan médico combinado para unificar el tono.",
     "que_es": ["Las manchas tienen causas distintas; por eso primero se diagnostican y luego se combina lo que tu piel necesita: despigmentantes, peelings, tecnologías y cuidado en casa.",
                "El melasma se controla con constancia y protección solar."],
     "ideal": ["Melasma", "Manchas por sol", "Manchas después del acné"],
     "datos": ("Plan según diagnóstico", "Variable", "Según el tratamiento", "Progresivo"),
     "faq": [("¿El melasma se cura?", "Se controla muy bien, pero puede volver con el sol o cambios hormonales. Por eso el mantenimiento es clave.")]},
    {"slug": "laser", "cat": "tecnologias", "nombre": "Láser",
     "corto": "Rejuvenecimiento, manchas, textura y lesiones vasculares.",
     "que_es": ["Tecnologías de luz que tratan manchas, textura, poros, arrugas finas y pequeñas lesiones vasculares, según el tipo de láser.",
                "El tipo y la intensidad se eligen según tu piel y el objetivo."],
     "ideal": ["Manchas y daño solar", "Textura y poros", "Arrugas finas"],
     "datos": ("1 a 3 sesiones", "30 a 60 minutos", "Según el láser: de ninguna a 5 días", "Progresivo"),
     "faq": [("¿Sirve para todas las pieles?", "Depende del láser y del fototipo. Por eso se valora antes.")]},
    {"slug": "depilacion-laser", "cat": "tecnologias", "nombre": "Depilación láser",
     "corto": "Reducción duradera del vello.",
     "que_es": ["Láser que actúa sobre el folículo para reducir el vello de forma progresiva y duradera, en rostro y cuerpo."],
     "ideal": ["Vello no deseado", "Foliculitis o vellos encarnados", "Piel sensible a la cera o la cuchilla"],
     "datos": ("6 a 8 sesiones o más", "15 a 60 minutos", "Ninguna", "Reducción progresiva"),
     "faq": [("¿Es definitiva?", "Logra una reducción importante y duradera; pueden requerirse sesiones de mantenimiento.")]},
    {"slug": "hifu", "cat": "tecnologias", "nombre": "HIFU",
     "corto": "Ultrasonido focalizado para tensar rostro y cuello sin cirugía.",
     "que_es": ["Ultrasonido de alta intensidad que calienta capas profundas de la piel para estimular colágeno y producir un efecto tensor.",
                "Sin agujas ni incisiones."],
     "ideal": ["Flacidez leve en rostro y cuello", "Pérdida de definición mandibular", "Mantenimiento"],
     "datos": ("1 sesión (refuerzo anual)", "60 a 90 minutos", "Ninguna", "Progresivo en 2 a 3 meses"),
     "faq": [("¿Duele?", "Se siente calor y molestia puntual, tolerable.")]},
    {"slug": "radiofrecuencia", "cat": "tecnologias", "nombre": "Radiofrecuencia",
     "corto": "Firmeza en rostro y cuerpo con calor controlado.",
     "que_es": ["Energía que calienta la dermis para contraer el colágeno y estimular uno nuevo, mejorando la firmeza de la piel en rostro y cuerpo."],
     "ideal": ["Flacidez leve", "Post parto o post liposucción (según indicación)", "Mantenimiento"],
     "datos": ("4 a 8 sesiones", "30 a 45 minutos", "Ninguna", "Progresivo"),
     "faq": [("¿Se puede combinar?", "Sí, con bioestimuladores o tratamientos corporales, según tu plan.")]},
    {"slug": "tratamientos-corporales", "cat": "tecnologias", "nombre": "Tratamientos corporales",
     "corto": "Celulitis, flacidez y grasa localizada con tecnologías y mesoterapia.",
     "que_es": ["Planes que combinan tecnologías, mesoterapia y drenajes para mejorar celulitis, flacidez y grasa localizada.",
                "No reemplazan una cirugía, pero son una excelente opción para mejorar y mantener."],
     "ideal": ["Celulitis", "Flacidez corporal", "Grasa localizada leve"],
     "datos": ("6 a 10 sesiones", "45 a 60 minutos", "Ninguna", "Progresivo"),
     "faq": [("¿Reemplazan la lipo?", "No. Mejoran la calidad y el contorno de forma no quirúrgica, con resultados más moderados.")]},
    {"slug": "sueroterapia", "cat": "bienestar", "nombre": "Sueroterapia",
     "corto": "Vitaminas y antioxidantes por vía intravenosa, bajo supervisión médica.",
     "que_es": ["Sueros formulados por un médico con vitaminas, minerales y antioxidantes, según tus necesidades.",
                "Se aplica con valoración médica previa y en un espacio adecuado."],
     "ideal": ["Cansancio", "Apoyo antioxidante", "Recuperación"],
     "datos": ("Según tu plan", "45 a 60 minutos", "Ninguna", "Según el objetivo"),
     "faq": [("¿La puede recibir cualquier persona?", "Requiere valoración médica previa para confirmar que sea segura para ti.")]},
    {"slug": "manejo-medico-del-peso", "cat": "bienestar", "nombre": "Manejo médico del peso",
     "corto": "Plan médico con seguimiento para bajar de peso de forma segura.",
     "que_es": ["Programa con valoración médica, exámenes, plan nutricional y, cuando está indicado, medicamentos formulados por el médico.",
                "El seguimiento cercano es parte del tratamiento."],
     "ideal": ["Sobrepeso u obesidad", "Preparación para una cirugía", "Mantenimiento después de bajar de peso"],
     "datos": ("Plan con controles periódicos", "Consulta de 45 minutos", "Ninguna", "Progresivo"),
     "faq": [("¿Me formulan medicamentos para bajar de peso?", "Solo si el médico los considera indicados y seguros para ti, después de valorarte.")]},
    {"slug": "nutricion", "cat": "bienestar", "nombre": "Nutrición",
     "corto": "Acompañamiento nutricional para tu salud y tus resultados.",
     "que_es": ["Plan de alimentación personalizado para mejorar tu salud, prepararte para una cirugía o mantener tus resultados."],
     "ideal": ["Antes o después de una cirugía", "Cambio de hábitos", "Mantenimiento del peso"],
     "datos": ("Según tu plan", "45 minutos", "Ninguna", "Progresivo"),
     "faq": [("¿Es necesaria antes de una cirugía?", "No siempre, pero ayuda a una mejor recuperación. Te lo recomendamos según tu caso.")]},
]

# ---------------------------------------------------------------- PREGUNTAS GENERALES (sin precios)
TODAS_CX = [c["slug"] for c in CIRUGIAS_NOON]
FAQ_NOON = [
    ("Valoración", "¿Por qué empezar con una valoración?", "Porque cada cuerpo y cada rostro son distintos. En la valoración el especialista te examina, escucha lo que quieres lograr y te dice qué tiene sentido para ti, qué no, y por qué."),
    ("Valoración", "¿Qué pasa en la valoración?", "Una consulta con el especialista del área: examen, preguntas sobre tu salud, explicación de opciones, riesgos y tiempos, y un plan por escrito. Si es una cirugía, sales con la orden de exámenes."),
    ("Valoración", "¿Cuánto cuesta un procedimiento?", "Cada plan es personal. Después de la valoración recibes un presupuesto por escrito con todo lo que incluye."),
    ("Valoración", "¿Puedo hacer la valoración si vivo en otra ciudad?", "Sí. Escríbenos por WhatsApp y te ayudamos a organizar tus fechas para que valoración, procedimiento y controles te queden en un mismo viaje."),

    ("Seguridad", "¿Dónde se hacen las cirugías?", "En salas de cirugía habilitadas (Q2). Nunca en consultorios."),
    ("Seguridad", "¿Qué exámenes me piden?", "Los prequirúrgicos que el especialista considere según tu edad, tu salud y el procedimiento. Sin exámenes en regla no hay cirugía."),
    ("Seguridad", "¿Pueden decirme que no?", "Sí, y es una buena señal. Si un procedimiento no es seguro o no tiene sentido para ti, te lo decimos."),
    ("Seguridad", "¿Qué riesgos tiene una cirugía?", "Toda cirugía tiene riesgos: sangrado, infección, problemas de cicatrización o relacionados con la anestesia, entre otros. Te los explicamos uno a uno y firmas un consentimiento informado."),

    ("Recuperación", "¿Me va a doler?", "Habrá molestia los primeros días, que se controla con el manejo del dolor que indica tu especialista."),
    ("Recuperación", "¿Necesito que alguien me cuide?", "En cirugía, sí: un acompañante adulto el día del procedimiento y, como mínimo, la primera noche."),
    ("Recuperación", "¿Cuántos controles tengo?", "Te acompañamos con controles hasta el alta."),
    ("Recuperación", "¿Cuándo vuelvo al ejercicio?", "Caminar, desde los primeros días. El ejercicio vuelve de forma gradual y solo con autorización de tu especialista."),

    ("Requisitos", "¿Desde qué edad me puedo operar?", "Por lo general desde los 18 años, con buen estado de salud. Algunos procedimientos, como la otoplastia, se valoran desde la infancia."),
    ("Requisitos", "Fumo, ¿puedo operarme?", "Debes suspender cigarrillo y vapeador varias semanas antes y después, porque afectan la cicatrización y aumentan los riesgos."),
    ("Requisitos", "¿Y si tengo una enfermedad o tomo medicamentos?", "Cuéntalo todo en la valoración. Muchas condiciones controladas no impiden tratarte, pero necesitamos saberlas para cuidarte."),

    ("Medicina estética", "¿Los tratamientos estéticos requieren valoración?", "Sí. Una valoración con la médica estética define qué tratamiento, qué producto y qué cantidad tienen sentido para ti."),
    ("Medicina estética", "¿Me voy a ver natural?", "Ese es el criterio de noon: realzar lo tuyo, no cambiar quién eres."),
    ("Medicina estética", "¿Puedo combinar tratamientos?", "Sí, muchas veces los mejores resultados vienen de combinar. Tu plan se arma según tu piel y tus objetivos."),

    ("Pagos", "¿Cómo separo la fecha de mi cirugía?", "Después de la valoración, reservas tu fecha con un abono. El saldo se paga antes de la cirugía."),
    ("Pagos", "Si me arrepiento, ¿me devuelven el abono?", "Sí, con una retención del 20% del valor abonado por gastos administrativos. El detalle está en los términos y condiciones."),
    ("Pagos", "¿Qué medios de pago reciben?", "Escríbenos por WhatsApp y te contamos los medios de pago disponibles."),

    ("Vengo de lejos", "¿Cuántos días debo quedarme después de una cirugía?", "Depende del procedimiento: como guía, entre una y tres semanas. El regreso lo autoriza tu cirujano en el control."),
    ("Vengo de lejos", "¿Cuándo puedo viajar en avión?", "Solo cuando tu cirujano lo autorice. Viajar antes de tiempo aumenta los riesgos."),
]
CATS_NOON = ["Valoración", "Seguridad", "Recuperación", "Requisitos", "Medicina estética", "Pagos", "Vengo de lejos"]
